lib/grantland_web/router.ex
defmodule GrantlandWeb.Router do
  use GrantlandWeb, :router

  import GrantlandWeb.UserAuth

  alias GrantlandWeb.EnsureRolePlug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GrantlandWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :guest do
    plug EnsureRolePlug, [:admin, :moderator, :user, :guest]
  end

  pipeline :user do
    plug EnsureRolePlug, [:admin, :moderator, :user]
  end

  pipeline :moderator do
    plug EnsureRolePlug, [:admin, :moderator]
  end

  pipeline :admin do
    plug EnsureRolePlug, :admin
  end

  ## Authentication routes

  scope "/", GrantlandWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  ## Authorization routes

  # TEST ROUTES
  scope "/", GrantlandWeb do
    pipe_through [:browser, :require_authenticated_user, :user]
    live "/user_dashboard", UserDashboardLive, :index
  end

  scope "/", GrantlandWeb do
    pipe_through [:browser, :require_authenticated_user, :admin]
    live "/admin_dashboard", AdminDashboardLive, :index
  end

  # REAL ROUTES

  # requires admin
  scope "/", GrantlandWeb do
    pipe_through [:browser, :require_authenticated_user, :admin]

    # Games
    live "/games", GameLive.Index, :index
    live "/games/new", GameLive.Index, :new
    live "/games/:id/edit", GameLive.Index, :edit

    live "/games/:id", GameLive.Show, :show
    # TOOD: Figure out what route this is?
    live "/games/:id/show/edit", GameLive.Show, :edit
  end

  scope "/", GrantlandWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    # Entries
    live "/entries/new", EntryLive.Index, :new
    live "/entries/:id/edit", EntryLive.Index, :edit
    live "/entries/:id/show/edit", EntryLive.Show, :edit

    # Pools
    live "/pools/new", PoolLive.Index, :new
    live "/pools/:id/edit", PoolLive.Index, :edit
    live "/pools/:id/show/edit", PoolLive.Show, :edit

    # Pool entries
    live "/pools/:id/show/entries/:entry_id/show/edit", PoolLive.Show, :edit_entry
    live "/pools/:id/show/entries/new", PoolLive.Show, :new_entry

    # Users
    live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id/edit", UserLive.Index, :edit

    live "/users/:id", UserLive.Show, :show
    live "/users/:id/show/edit", UserLive.Show, :edit

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  # Routes open to all

  scope "/", GrantlandWeb do
    pipe_through :browser

    live "/", PageLive, :index

    # Entries
    live "/entries", EntryLive.Index, :index
    live "/entries/:id", EntryLive.Show, :show

    # Pools
    live "/pools", PoolLive.Index, :index
    live "/pools/:id", PoolLive.Show, :show

    # FOR SOME LAYOUT TESTING
    live "/layout", LayoutLive, :index
    live "/new_layout", NewLayoutLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", GrantlandWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GrantlandWeb.Telemetry
    end
  end
end

lib/grantland_web/live/layout_live.ex
defmodule GrantlandWeb.LayoutLive do
  use GrantlandWeb, :live_view

  @impl true
  def mount(_params, session, socket) do
    socket = assign_defaults(session, socket)
    {:ok, socket}
  end
end

lib/grantland_web/views/layout_view.ex
defmodule GrantlandWeb.LayoutView do
  use GrantlandWeb, :view
end

lib/grantland_web/templates/layout/_links.html.leex
  <%= button "Pools", to: Routes.pool_index_path(@conn, :index), method: :get %>
  <%= button "Entries", to: Routes.entry_index_path(@conn, :index), method: :get %>
  <%= if @current_user && @current_user.role == :admin do %>
    <%= button "Games", to: Routes.game_index_path(@conn, :index), method: :get %>
  <% end  %>

lib/grantland_web/templates/layout/_user_menu.html.eex
<%= cond do %>
  <%= @current_user -> %>
    <p>
      <%= @current_user.email %> |
      <%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %> |
      <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %>
    </p>
  <% !@current_user && !users_path?(@conn.path_info) -> %>
    <p>
      <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
      <%= link "Log in", to: Routes.user_session_path(@conn, :new) %>
    </p>
  <% true -> %>
    <p></p>
<% end %>

lib/grantland_web/templates/layout/app.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<%= @inner_content %>

lib/grantland_web/templates/layout/live.html.leex
<p class="alert alert-info" role="alert"
  phx-click="lv:clear-flash"
  phx-value-key="info"><%= live_flash(@flash, :info) %></p>

<p class="alert alert-danger" role="alert"
  phx-click="lv:clear-flash"
  phx-value-key="error"><%= live_flash(@flash, :error) %></p>

<%= @inner_content %>

lib/grantland_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Grantland" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <section class="layout">
      <div class="header">
        <h1><a href="/">Grantland</a></h1>
        <div class="hero-logo">
          <div class="slogan">Let's Play</div>
        </div>
      </div>

      <nav class="nav">
        <%= render "_user_menu.html", assigns %>
      </nav>

      <%= @inner_content %>

      <div class="footer">
        <p>
          ikn
        </p>
      </div>
    </section>
  </body>